version: 2
jobs:
  build_windows_linux:
    docker:
      # specify the version you desire here
      - image: electronuserland/builder:wine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run dist:windows-linux

      - store-artifacts:
          path: dist

  build_mac:
    macos:
      xcode: "9.3.0"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run dist:mac

      - store-artifacts:
          path: dist

workflows:
  version: 2
  build:
    jobs:
      - build_windows_linux:
        filters:
            branches:
              only: release
      - build_mac:
          filters:
            branches:
              only: release
